spring:
  application:
    name: micro-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.23.1.227:3306/youlai?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#security:
#  basic:
#    enabled: false
#management:
#  security:
#    enabled: false

  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678